import {Invoice, Invoicing} from '../lib/invoicing';
import {DateTime, Info} from 'luxon';
import {inspect} from 'util';
import {mockContract, mockInvoice, mockReceiver} from './mock.factory';

describe('initial test', () => {
    it('should always be OK', () => {
        expect(1).toBe(1);
    });
});

describe('contract tests', () => {
    it('should create a contract', () => {
        const contract = mockContract();
        console.log('contract: ', inspect(contract));
        expect(contract).toBeTruthy();
        expect(contract.header.objectType === 'contracts');
        expect(contract.isActive()).toBeTruthy();
        expect(contract.isFuture()).toBeFalsy();
        expect(contract.isInvoiceable()).toBeTruthy();
        console.log('duration in days: ', contract.durationInDays);
        expect(contract.durationInDays).toBeGreaterThanOrEqual(89);
    });
});

describe('invoice tests', () => {
    it('should create an invoice from contract - with id, period, quantity and vat', () => {
        const contract = mockContract();
        const period = 'Januar 2019';
        const quantity = 10;
        const vatPercentage = 19.0;
        const invoice = Invoicing.createInvoiceFromContract(contract, period, quantity, vatPercentage, '5901');
        console.log('invoice: ', invoice);
        expect(invoice).toBeTruthy();
        expect(invoice.header.objectType).toBe('invoices');
        expect(invoice.vatPercentage).toBe(19.0);
        expect(invoice.netValue).toEqual(contract.items[0].pricePerUnit * quantity);
        expect(invoice.vatAmount).toEqual(invoice.netValue * vatPercentage / 100);
        expect(invoice.grossValue).toEqual(invoice.netValue + invoice.vatAmount);
        expect(invoice.cashDiscountBaseAmount).toEqual(invoice.grossValue);
        expect(invoice.cashDiscountAmount).toEqual(invoice.cashDiscountBaseAmount * invoice.cashDiscountPercentage / 100);
        expect(invoice.paymentAmount).toEqual(invoice.grossValue - invoice.cashDiscountAmount);
        const issuedAt = invoice.header.issuedAt ? DateTime.fromJSDate(invoice.header.issuedAt) : DateTime.utc().startOf('day');
        const dtCashDiscountDate = DateTime.fromJSDate(invoice.cashDiscountDate);
        const isCashDiscountDateOk = dtCashDiscountDate.equals(issuedAt.plus({days: invoice.header.cashDiscountDays}));
        expect(isCashDiscountDateOk).toBeTruthy();
        const dtDueDate = DateTime.fromJSDate(invoice.dueDate);
        const isDueDateOk = dtDueDate.equals(issuedAt.plus({days: invoice.header.dueInDays}));
        expect(isDueDateOk).toBeTruthy();
        expect(invoice.isBilled()).toBeFalsy();
        expect(invoice.isDue()).toBeFalsy();
        expect(invoice.isOpen()).toBeTruthy();
        expect(invoice.isPaid()).toBeFalsy();
        expect(invoice.items.length).toBe(1);
        expect(invoice.items[0].id).toBe(1);
        expect(invoice.items[0].contractItemId).toBe(contract.items[0].id);
        expect(invoice.items[0].description).toEqual(contract.items[0].description);
        expect(invoice.items[0].quantity).toBe(quantity);
        expect(invoice.items[0].quantityUnit).toEqual(contract.items[0].priceUnit);
        expect(invoice.items[0].pricePerUnit).toEqual(contract.items[0].pricePerUnit);
        expect(invoice.items[0].cashDiscountAllowed).toEqual(contract.items[0].cashDiscountAllowed);
        expect(invoice.items[0].vatPercentage).toEqual(vatPercentage);
        expect(invoice.items[0].discountableValue).toEqual(invoice.items[0].grossValue);
        expect(invoice.items[0].grossValue).toEqual(invoice.items[0].netValue + invoice.items[0].vatValue);
        expect(invoice.items[0].netValue).toEqual(invoice.items[0].quantity * invoice.items[0].pricePerUnit);
        expect(invoice.items[0].vatValue).toEqual(invoice.items[0].netValue * vatPercentage / 100);
    });
    it('should create an invoice from contract - without id, period, quantity and vat', () => {
        const contract = mockContract();
        const invoice = Invoice.createFromContract(contract);
        console.log('invoice: ', invoice);
        invoice.header.id = '5901';
        invoice.header.vatPercentage = 19.0;
        invoice.header.billingPeriod = 'Januar 2019';
        invoice.items[0].quantity = 10;
        invoice.items[0].vatPercentage = invoice.header.vatPercentage;
        expect(invoice).toBeTruthy();
        expect(invoice.header.objectType).toBe('invoices');
        expect(invoice.vatPercentage).toBe(19.0);
        expect(invoice.netValue).toEqual(contract.items[0].pricePerUnit * 10);
        expect(invoice.vatAmount).toEqual(invoice.netValue * 19.0 / 100);
        expect(invoice.grossValue).toEqual(invoice.netValue + invoice.vatAmount);
        expect(invoice.cashDiscountBaseAmount).toEqual(invoice.grossValue);
        expect(invoice.cashDiscountAmount).toEqual(invoice.cashDiscountBaseAmount * invoice.cashDiscountPercentage / 100);
        expect(invoice.paymentAmount).toEqual(invoice.grossValue - invoice.cashDiscountAmount);
        const issuedAt = invoice.header.issuedAt ? DateTime.fromJSDate(invoice.header.issuedAt) : DateTime.utc().startOf('day');
        const dtCashDiscountDate = DateTime.fromJSDate(invoice.cashDiscountDate);
        const isCashDiscountDateOk = dtCashDiscountDate.equals(issuedAt.plus({days: invoice.header.cashDiscountDays}));
        expect(isCashDiscountDateOk).toBeTruthy();
        const dtDueDate = DateTime.fromJSDate(invoice.dueDate);
        const isDueDateOk = dtDueDate.equals(issuedAt.plus({days: invoice.header.dueInDays}));
        expect(isDueDateOk).toBeTruthy();
        expect(invoice.isBilled()).toBeFalsy();
        expect(invoice.isDue()).toBeFalsy();
        expect(invoice.isOpen()).toBeTruthy();
        expect(invoice.isPaid()).toBeFalsy();
        expect(invoice.items.length).toBe(1);
        expect(invoice.items[0].id).toBe(1);
        expect(invoice.items[0].contractItemId).toBe(contract.items[0].id);
        expect(invoice.items[0].description).toEqual(contract.items[0].description);
        expect(invoice.items[0].quantity).toBe(10);
        expect(invoice.items[0].quantityUnit).toEqual(contract.items[0].priceUnit);
        expect(invoice.items[0].pricePerUnit).toEqual(contract.items[0].pricePerUnit);
        expect(invoice.items[0].cashDiscountAllowed).toEqual(contract.items[0].cashDiscountAllowed);
        expect(invoice.items[0].vatPercentage).toEqual(19.0);
        expect(invoice.items[0].discountableValue).toEqual(invoice.items[0].grossValue);
        expect(invoice.items[0].grossValue).toEqual(invoice.items[0].netValue + invoice.items[0].vatValue);
        expect(invoice.items[0].netValue).toEqual(invoice.items[0].quantity * invoice.items[0].pricePerUnit);
        expect(invoice.items[0].vatValue).toEqual(invoice.items[0].netValue * 19.0 / 100);
    });
    it('should create an invoice from data', () => {
        const invoice = mockInvoice();
        console.log('invoice: ', invoice);
        expect(invoice).toBeTruthy();
        expect(invoice.header.objectType).toBe('invoices');
        expect(invoice.vatPercentage).toBe(19.0);
        expect(invoice.netValue).toEqual(invoice.items[0].pricePerUnit * invoice.items[0].quantity);
        expect(invoice.vatAmount).toEqual(invoice.netValue * invoice.vatPercentage / 100);
        expect(invoice.grossValue).toEqual(invoice.netValue + invoice.vatAmount);
        expect(invoice.cashDiscountBaseAmount).toEqual(invoice.grossValue);
        expect(invoice.cashDiscountAmount).toEqual(invoice.cashDiscountBaseAmount * invoice.cashDiscountPercentage / 100);
        expect(invoice.paymentAmount).toEqual(invoice.grossValue - invoice.cashDiscountAmount);
        const issuedAt = invoice.header.issuedAt ? DateTime.fromJSDate(invoice.header.issuedAt) : DateTime.utc().startOf('day');
        const dtCashDiscountDate = DateTime.fromJSDate(invoice.cashDiscountDate);
        const isCashDiscountDateOk = dtCashDiscountDate.equals(issuedAt.plus({days: invoice.header.cashDiscountDays}));
        expect(isCashDiscountDateOk).toBeTruthy();
        const dtDueDate = DateTime.fromJSDate(invoice.dueDate);
        const isDueDateOk = dtDueDate.equals(issuedAt.plus({days: invoice.header.dueInDays}));
        expect(isDueDateOk).toBeTruthy();
        expect(invoice.isBilled()).toBeFalsy();
        expect(invoice.isDue()).toBeFalsy();
        expect(invoice.isOpen()).toBeTruthy();
        expect(invoice.isPaid()).toBeFalsy();
        expect(invoice.items.length).toBe(1);
        expect(invoice.items[0].id).toBe(1);
        expect(invoice.items[0].contractItemId).toBe(1);
        expect(invoice.items[0].description).toEqual('Arbeitszeit');
        expect(invoice.items[0].quantity).toBe(10);
        expect(invoice.items[0].quantityUnit).toEqual('Std.');
        expect(invoice.items[0].pricePerUnit).toEqual(123.45);
        expect(invoice.items[0].cashDiscountAllowed).toBeTruthy();
        expect(invoice.items[0].vatPercentage).toEqual(19.0);
        expect(invoice.items[0].discountableValue).toEqual(invoice.items[0].grossValue);
        expect(invoice.items[0].grossValue).toEqual(invoice.items[0].netValue + invoice.items[0].vatValue);
        expect(invoice.items[0].netValue).toEqual(invoice.items[0].quantity * invoice.items[0].pricePerUnit);
        expect(invoice.items[0].vatValue).toEqual(invoice.items[0].netValue * 19.0 / 100);
    });
});

describe('receiver tests', () => {
    it('should create a receiver', () => {
        const receiver = mockReceiver();
        console.log('receiver: ', inspect(receiver));
        expect(receiver).toBeTruthy();
        expect(receiver.header.objectType === 'receivers');
        expect(receiver.isActive()).toBeTruthy();
        expect(receiver.address.country).toEqual('DE');
    });
});

